version: "3"

includes:
  docs:
    taskfile: ./tasks/docmd/Taskfile.yml
    dir: ./tasks/docmd
  ci:
    taskfile: ./.github/Taskfile.yml
    dir: ./

tasks:
  build:
    desc: Build all Go packages
    run: when_changed
    method: timestamp
    sources:
      - "**/*.go"
      - "**/*.zirr"
      - exclude: Cavefile
      - exclude: examples/
      - exclude: _tasks/
      - exclude: "**/_t"
      - go.mod
      - go.sum
    generates:
      - zirric
    cmds:
      - go build -v ./...
      - go build ./cmd/zirric

  test:
    desc: Run all tests (Go + CLI)
    cmds:
      - task: test:go
      - task: test:cli
      - task: test:stdlib

  test:go:
    desc: Run all Go tests
    sources:
      - "**/*.go"
      - "**/*.zirr"
      - exclude: Cavefile
      - exclude: examples/
      - exclude: _tasks/
      - go.mod
      - go.sum
    cmds:
      - go test ./... -race

  test:cli:
    desc: Run CLI integration tests (bats)
    run: when_changed
    method: timestamp
    deps:
      - build
    sources:
      - testing/
      - zirric
    cmds:
      - bats testing

  test:stdlib:
    desc: Run Zirric Stdlib tests
    run: always
    method: timestamp
    deps:
      - build
    sources:
      - zirric
      - "**/*.zirr"
      - Cavefile
    cmds:
      - ./zirric task run test

  gen:golden:
    desc: Regenerate formatter golden files
    cmds:
      - go test ./pkg/codefmt -update

  bench:
    desc: Run all Benchmarks
    sources:
      - "**/*.go"
      - "**/*.zirr"
      - go.mod
      - go.sum
    cmds:
      - go test ./... -count=1 -bench=.

  fmt:
    desc: Format
    deps:
      - build
    cmds:
      - gofmt -w .
      - dprint fmt --config dprint.json
      - ./zirric fmt .

  check:
    desc: Full validation (format, vet, build, test)
    deps:
      - build
    cmds:
      - gofmt -l .
      - dprint check --config dprint.json
      - ./zirric fmt --check .
      - golangci-lint run
      - go vet ./...
      - goreleaser check
      - go build -v ./...
      - go test ./...

  goreleaser:snapshot:
    desc: Build GoReleaser snapshot artifacts
    cmds:
      - goreleaser build --snapshot --clean
