version: "3"

includes:
  docs:
    taskfile: ./tasks/docmd/Taskfile.yml
    dir: ./tasks/docmd
  ci:
    taskfile: ./.github/Taskfile.yml
    dir: ./

tasks:
  build:
    desc: Build all Go packages
    cmds:
      - go build -v ./...

  test:
    desc: Run all Go tests
    sources:
      - "**/*.go"
      - "**/*.zirr"
      - go.mod
      - go.sum
    cmds:
      - go test ./... -race

  bench:
    desc: Run all Benchmarks
    sources:
      - "**/*.go"
      - "**/*.zirr"
      - go.mod
      - go.sum
    cmds:
      - go test ./... -count=1 -bench=.

  fmt:
    desc: Format
    cmds:
      - gofmt -w .
      - dprint fmt --config dprint.json

  check:
    desc: Full validation (format, vet, build, test)
    cmds:
      - gofmt -l .
      - dprint check --config dprint.json
      - golangci-lint run
      - go vet ./...
      - goreleaser check
      - go build -v ./...
      - go test ./...

  goreleaser:snapshot:
    desc: Build GoReleaser snapshot artifacts
    cmds:
      - goreleaser build --snapshot --clean
