version: "3"

tasks:
  install:
    cmds:
      - npm install

  build:
    desc: Build docs site
    deps: [install]
    cmds:
      - npm run build

  dev:
    desc: Run docs dev server
    deps: [install]
    cmds:
      - npm run build
